### ISSUE TITLE
Error loading Homebridge after install

### ISSUE THREAD

**Issue by simonrb2000** [robertvorthman/homebridge-marantz-volume#3]
After installing this and trying to run homebridge I get the following error:-

Cheers

```
[7/24/2016, 1:13:04 AM] Loaded plugin: homebridge-controllerlink
[7/24/2016, 1:13:05 AM] Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'
[7/24/2016, 1:13:05 AM] ---
[7/24/2016, 1:13:09 AM] Loaded plugin: homebridge-edomoticz
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-edomoticz.eDomoticz'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-edomoticz.eDomoticz'
[7/24/2016, 1:13:09 AM] ---
[7/24/2016, 1:13:09 AM] Loaded plugin: homebridge-legacy-plugins
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.AD2USB'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.Carwings'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.ELKM1'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.FileSensor'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.HomeMatic'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.LiftMaster'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.Lockitron'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.Tesla'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.WeMo'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.X10'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.iControl'
[7/24/2016, 1:13:09 AM] Registering accessory 'homebridge-legacy-plugins.mpdclient'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.Domoticz'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.HomeSeer'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.ISY'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.LIFx'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.MiLight'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.Openhab'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.SmartThings'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.TelldusLive'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.Wink'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.YamahaAVR'
[7/24/2016, 1:13:09 AM] Registering platform 'homebridge-legacy-plugins.ZWayServer'
[7/24/2016, 1:13:09 AM] ---
[7/24/2016, 1:13:19 AM] Loaded plugin: homebridge-marantz-volume
[7/24/2016, 1:13:19 AM] Registering accessory 'homebridge-marantz-volume.marantz-volume'
[7/24/2016, 1:13:19 AM] ---
[7/24/2016, 1:13:19 AM] Loaded config.json with 2 accessories and 0 platforms.
[7/24/2016, 1:13:19 AM] ---
[7/24/2016, 1:13:19 AM] Loading 2 accessories...
[7/24/2016, 1:13:19 AM] [Stereo Volume] Initializing marantz-volume accessory...
/usr/local/lib/node_modules/homebridge/lib/api.js:46
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:233:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by robertvorthman** [comment]
What version of Homebridge do you have?

**Comment by simonrb2000** [comment]
0.34 mate

On 24 Jul 2016, at 01:48, robertvorthman <notifications@github.com<mailto:notifications@github.com>> wrote:

What version of Homebridge do you have?

**Comment by robertvorthman** [comment]
I'm not sure what the problem could be. Could you please share the section of your config.json related to this plugin?

**Comment by simonrb2000** [comment]
This is my config file, Cheers

{
"bridge": {
"name": "Homebridge",
"username": "DD:33:4E:F4:DF:31",
"port": 51927,
"pin": "031-45-154"
},

"accessories": [{
"accessory": "marantz-volume",
"name": "Stereo Volume",
"host": "192.168.1.12",
"maxVolume": 80
}, {

"platforms": [{
"platform": "eDomoticz",
"name": "eDomoticz",
"server": "127.0.0.1",
"port": "8080",
"roomid": "4",
"loadscenes": "0"
}, {
"platform": "HomeBridgeControllerLink"
}, {
"platform": "eDomoticz",
"name": "eDomoticz",
"server": "192.168.1.27",
"port": "8080",
"roomid": "2",
"loadscenes": "0"
}]
}]
}
On 24 Jul 2016, at 12:26, robertvorthman <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure what the problem could be. Could you please share the section of your config.json related to this plugin?

**Comment by robertvorthman** [comment]
Your config.js is incorrectly structured.  Your Platforms are inside of Accessories.  You need to close the accessories array first, so that accessories and platforms are siblings, not parent-child.

Paste your config.json into http://jsbeautifier.org/ so it's easier to see the structure.

Structure your config.json like in this example:
https://github.com/nfarina/homebridge/blob/master/config-sample.json

Let me know if you need help.

**Comment by simonrb2000** [comment]
Ah! My bad. I shall have a play after F1! Thank you..

Sent from my iPad

On 24 Jul 2016, at 12:40, robertvorthman <notifications@github.com<mailto:notifications@github.com>> wrote:

Your config.js is incorrectly structured. Your Platforms are inside of Accessories. You need to close the accessories array first, so that accessories and platforms are siblings, not parent-child.

Using http://jsbeautifier.org/ makes it easier to see the structure.

Structure your config.json like in this example:
https://github.com/nfarina/homebridge/blob/master/config-sample.json

Let me know if you need help.

##

**Comment by simonrb2000** [comment]
Working mate, thank you!! And it is on a Denon Amp.

On 24 Jul 2016, at 12:40, robertvorthman <notifications@github.com<mailto:notifications@github.com>> wrote:

Your config.js is incorrectly structured. Your Platforms are inside of Accessories. You need to close the accessories array first, so that accessories and platforms are siblings, not parent-child.

Using http://jsbeautifier.org/ makes it easier to see the structure.

Structure your config.json like in this example:
https://github.com/nfarina/homebridge/blob/master/config-sample.json

Let me know if you need help.

**Comment by robertvorthman** [comment]
I'm glad it is working for you.  Thanks for telling me it works with your Denon,  I have updated the readme so other people know Denons are verified compatible.
